- include: apt_install_packages.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
- include: yum_install_packages.yml
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
- include: enable_drivers.yml   
