---
- name: Delete Image
  file: path="{{ cd_images_path }}/{{ result_domain_name }}.img" state=absent 
  when: cd_delete_uploaded_image

- stat: path="{{ cd_images_path }}/{{ result_domain_name }}.img"
  register: image_file

- name: Copy VM Image
  command: >
    cp
    {{ cd_base_images[vm.distro_release] }}
    {{ result_domain_name }}.img
  args:
    chdir: "{{ cd_images_path }}"
    creates: "{{ cd_images_path }}/{{ result_domain_name }}.img"
  register: copy_image_result
  when: vm.base_image_mode == 'copy' and image_file.stat.exists == False

- name: Snapshot VM Image
  command: >
    qemu-img create
    -f qcow2
    -b {{ cd_base_images[vm.distro_release] }}
    {{ result_domain_name }}.img
  args:
    chdir: "{{ cd_images_path }}"
    creates: "{{ cd_images_path }}/{{ result_domain_name }}.img"
  register: snapshot_image_result
  when: vm.base_image_mode == 'snapshot' 

- name: Resize VM Image
  command: >
    qemu-img resize
    {{ result_domain_name }}.img
    {{ vm.disk_size }}
  args:
    chdir: "{{ cd_images_path }}"
  when: (vm.disk_size is defined) and image_file.stat.exists == False
