---
- name: Delete Image
  file: path="{{ cd_images_path }}/{{ result_domain_name }}.img" state=absent 
- name: Delete Cloud config image
  file: path="{{ cd_images_path }}/{{ result_domain_name }}.cloud-config.img" state=absent 
- name: Delete Cloud Config
  file: path="{{ cd_images_path }}/{{ result_domain_name }}.cloud-config" state=absent 
- name: Delete Ifaces
  file: path="{{ cd_images_path }}/{{ result_domain_name }}.ifaces" state=absent 
- name: Delete Network Config
  file: path="{{ cd_images_path }}/{{ result_domain_name }}.network-config" state=absent 

