---
- name: Set snapd proxy
  copy:
    dest: /etc/systemd/system/snapd.service.d/override.conf
    content: |
      [Service]
      Environment=http_proxy={{ proxy_env.http_proxy }} https_proxy={{ proxy_env.https_proxy }}
  when: ansible_distribution_release == "bionic"

- name: Set env http proxy
  lineinfile:
    path: /etc/environment
    regexp: http_proxy
    line: http_proxy={{ proxy_env.http_proxy }}

- name: Set env https proxy
  lineinfile:
    path: /etc/environment
    regexp: https_proxy
    line: https_proxy={{ proxy_env.https_proxy }}

- name: reload systemd
  sudo: yes
  command: systemctl daemon-reload
  when: ansible_distribution_release == "bionic"

- name: Reload snapd
  service:
    name: snapd
    state: restarted
  when: ansible_distribution_release == "bionic"
